### ISSUE TITLE
No build/syntax check in 4.0.1

### ISSUE THREAD

**Issue by mileusna** [joefitzgerald/go-plus#384]
The main feature is missing or it doesn't work on both of my Macs after update, build/syntax check on this new version 4.0.1. It does nothing on save, also I can't find "Syntax check" in Packages -> Go as well. Also, in any of this new installed packaged I can't find the settings for "Check syntax on save" like in 3.5? Am I doing something wrong?

**Comment by joefitzgerald** [comment]
This is now provided by [`gotype`](https://godoc.org/golang.org/x/tools/cmd/gotype) in [gometalinter-linter](https://atom.io/packages/gometalinter-linter). What are you not seeing that you are expecting to see?

**Comment by mileusna** [comment]
I don't see errors. I save the file with errors and nothing happens. go-plus doesn't report any compiler error. I started looking for settings, in 3.5 there was a check box "check syntax on save" or something like that. I thought that option is maybe unchecked after update, but I couldn't find those settings in new go-* packages.

On other Mac now I see messages, but it reports some strange errors by gotype like "could not import fmt, can't find import". GOPATH is correct. Also I need only gotype on save, no golint, but it looks like it is all or nothing in 4.0.1.

Everything worked fine before the update on both machines.

I will investigate this tomorrow again.

**Comment by joefitzgerald** [comment]
It's not all or nothing. You can configure the gometalinter arguments. Go to the package settings for gometalinter-linter.

Can you put together a gist that reproduces the issue for me?

**Comment by averrin** [comment]
Hi. Today update atom to 1.7beta0 & go-plus
Do some errors in code. Save.
See only warnings in bottom doc. No orange/red waves in code, no information about failed build=(
Plz, return all of this!!!! :sob:

**Comment by mileusna** [comment]
I only see one input line for params in gometalinter-linter settings.

Also, in Packages menu there is only on item under "gometalinter" "Install and Update Tools", and it does nothing when it is clicked.

![screen shot 2016-03-18 at 12 33 13](https://cloud.githubusercontent.com/assets/4697935/13876591/a4f0c85e-ed05-11e5-812c-d0372c2655ed.png)
![screen shot 2016-03-18 at 12 32 54](https://cloud.githubusercontent.com/assets/4697935/13876590/a4f08236-ed05-11e5-898e-9ce2f77f1f0d.png)

**Comment by brosner** [comment]
This is a big regression for me too. I looked through all the gometalinter options and none of them do what go-plus used to do, `go build`. Compiling using `go build` on the command line shows many compiler errors, but nothing is reported in the editor.

While I like the direction of gometalinter (using Atom's linter) it either needs to support `go build` or this functionality needs to be restored here (or perhaps mentioned in the release notes as backward incompatible).

Despite the regression, I find 4.0 a very good direction for this project. Thank you @joefitzgerald for your hard work.

**Comment by averrin** [comment]
In addition about go build: there is nice plugin "glow" which needs @emit("dispatch-start") before actual building. I think glow is good candidate to merge in "build" functionality

**Comment by joefitzgerald** [comment]
@brosner `gotype` does what go-plus used to do when checking files for syntax errors. If you run:

```
--vendor, --disable-all, --enable=vetshadow, --enable=gotype, --enable=golint, --tests, --json, ./...
```

... from the terminal in the directory you're in, you should see the exact same output that you would have seen when using go-plus 3.5.x prior. You should also see this reflected in the editor. Linter provides the ability to see errors for only the current file or errors for the whole project.

The current default arguments run _more_ linters than we were running before.

**Comment by swsnider** [comment]
Why would a simple upgrade cause more linters than I had previously selected to be turned on? This significantly disrupted my dev flow, since I turn of standard go linting due to a difference of opinion about doc comments. When I upgraded go-plus as prompted, gometalinter-linter started linting doc comments again, so I disabled it, assuming the go-plus package was largely doing the same thing. The fact that I had to come here to discover that you'd entirely move the functionality was surprising, as was the fact that my previous settings were not migrated automatically.

**Comment by zmb3** [comment]
More linters are enabled due to the switch from manually invoking `go vet` and `golint` to using `gometalinter` for linting.  This information was explained in the [release notes ](https://github.com/joefitzgerald/go-plus/releases/tag/v4.0.0)for the upgrade that you installed.

As an aside - I wouldn't consider 4.0 a simple upgrade.  v3.4.3 to v3.4.4 is a simple upgrade.  A new major version usually indicates more significant changes.

**Comment by mileusna** [comment]
Ok, I see what you mean. On one Mac by tweeking params I managed to get only gotype without golint. However, on that Mac gotype is not working properly, it can't import standard packages and report errors. It is the same with gotype from command line, so I have to fix gotype that and it will work I guess.

On other Mac, ironically, gotype is working properly from command line, but unfortunattly I still can't get any result in Atom. GOPATH is correct, for example goimport is executed, I can see that, but no errors from gotype. I see green "No issues" mark in status bar. "Lint on save" is checked in go-plus settings.

I have noticed on both Macks that on save, the main editor window lose focus. If I press any key on save, it will put me at the bottom of the document. It happens only in Go documents after I have updated to 4.0.1 so it also has something to do with go-plus

**Comment by mileusna** [comment]
After fixing gotype I resolved issues on the first Mac. However, there is that bug with saving that editor window lose focus. I guess I should open another issue with that since it is unrelated to gometalinter.

**Comment by joefitzgerald** [comment]
@mileusna please update `gofmt` to v1.0.3. The cursor moving to the end of the file issue was fixed earlier today.

**Comment by mileusna** [comment]
Thank you, I'm also close to this one. It turns out that gometalint command had some PATH related errors. I have seen them when I tried gometalint from command line. After fixing environment PATH, it works on another Mac as well. I get gotype errors, but now I got this, even if golint working properly and in path (although I don't actually need golint and have diabled it in gometalinter params)
![screen shot 2016-03-18 at 18 59 02](https://cloud.githubusercontent.com/assets/4697935/13887523/61f968ee-ed3c-11e5-90f8-3b77c236c993.png)

But I'm closer and closer :)

Sorry for all the noise, but it was very painful upgrade. :)

**Comment by joefitzgerald** [comment]
@mileusna I think perhaps there was an issue in installing the tools for `gometalinter`. Can you please try running `gometalinter --install --update` from the terminal? This should re-download and install all the requisite tools.

**Comment by mileusna** [comment]
Same after the command. 

If I add --enable=golint I even see golint errors in Atom, so the golint is there, but I still get that large error box that I attached above.

![screen shot 2016-03-18 at 19 37 33](https://cloud.githubusercontent.com/assets/4697935/13888293/05a3f8d4-ed41-11e5-8ada-6e568acd3aa3.png)

```
$ gometalinter --install --update
Installing:
  dupl
  goconst
  errcheck
  structcheck
  varcheck
  unconvert
  golint
  gotype
  ineffassign
  goimports
  aligncheck
  interfacer
  lll
  deadcode
  gocyclo
```

**Comment by mileusna** [comment]
![screen shot 2016-03-18 at 19 44 57](https://cloud.githubusercontent.com/assets/4697935/13888481/f834eb94-ed41-11e5-8773-c04c3acec11e.png)

**Comment by joefitzgerald** [comment]
It seems as though you have another package installed that is running `golint`. Can you paste the output from `apm list` on the command line?

**Comment by mileusna** [comment]
Correct! I had `linter-golinter` installed, I guess I have installed it yesterday for some reason while trying to fix all this mess. After uninstall of `linter-golinter` everything is working finally.

Bottom line, it was the PATH issue with `gometalinter` which requires that `$GOPATH/bin` is in environment PATH, but I was unable to see that until I was not aware what should I look for and started `gometalinter` from command line. Perhapse you should somehow check this errors from `gometalinter` and display it to Atom users to be aware that they should fix PATH.

Thank you for your help, keep up the good work.

**Comment by joefitzgerald** [comment]
@mileusna yes, I agree there could be enhanced logic in `gometalinter` to cater to scenarios when a user does not have `$GOPATH/bin` in their `PATH`. I have created https://github.com/alecthomas/gometalinter/issues/102 to track this.

**Comment by atombender** [comment]
I hope you will reopen this. `gotype` is _not_ analogous to go-plus 3.5's syntax checking, due to [this issue](https://github.com/golang/go/issues/10249#issuecomment-86671707) — `gotype` requires that referenced packages are not just built, but _installed_. This requirement is nonsensical for an editor linter; what are you supposed to do, install every package in your project every time you make a change?

For example, when I enabled the new linting, I get tons of errors this like this:

![screen shot 2016-03-21 at 12 51 51](https://cloud.githubusercontent.com/assets/50314/13926669/c16c5420-ef63-11e5-8644-9cbc1fbec2f4.png)

That's no ~~moon~~ syntax error.

I propose that 3.5's syntax checker is added to `go-plus` unless there's a way to configure `gometalinter` to give us syntax checks. Because this counts as a major regression.

**Comment by atombender** [comment]
Also see [this `gometalinter` issue discussion](https://github.com/alecthomas/gometalinter/issues/91) about the problems with `gotype`.

**Comment by joefitzgerald** [comment]
Actually, you also need to run `go install ./...` for `gocode` to function correctly too. The bigger issue with `gotype` is related to it's inability to work with the `_test` package.

**Comment by pierrre** [comment]
@joefitzgerald `gocode` has the `autobuild` option

**Comment by atombender** [comment]
@joefitzgerald: That is sad. How can people work like this? Do you run some kind of watcher that installs all your packages whenever you make an editor change? I don't see any other way. Running `go install  ./...` in the terminal at regular intervals would waste so much time.

**Comment by joefitzgerald** [comment]
@atombender can you please join Slack (https://gophersinvite.herokuapp.com) [#go-plus] to discuss further? I am working on a package that will do precisely what you describe on save of a .go file.

**Comment by joefitzgerald** [comment]
@pierrre yes, but @nsf doesn't recommend using `autobuild`: https://github.com/joefitzgerald/go-plus/issues/350#issuecomment-176578554

**Comment by nsf** [comment]
Just FYI, I don't recommend `autobuild` because I'm not sure if it's correctly implemented or not. Autobuild daemon as an idea is okay, but I never wanted gocode to be one, partly because I don't use autobuild feature. Building stuff is not easy and doing anything in that area until community decides what it wants when it comes to managing deps seems like a waste of time. I myself happen to be using `gb`. So for me `autobuild` in gocode is useless.
